
PyTorch是什么?
================
    

Tensors（张量）
---------------





Tensors与Numpy中的 ndarrays类似，但是在PyTorch中
Tensors 可以使用GPU进行计算.



In [1]:
import torch

创建一个 5x3 矩阵, 但是未初始化:



In [5]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


创建一个随机初始化的矩阵:



In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9024, 0.4379, 0.6050],
        [0.9608, 0.2475, 0.3841],
        [0.8427, 0.0180, 0.5167],
        [0.2907, 0.2221, 0.3680],
        [0.2027, 0.8143, 0.7090]])


创建一个0填充的矩阵，数据类型为long:



In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


创建tensor并使用现有数据初始化:



In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖

In [9]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 方法来创建对象
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 覆盖 dtype!
print(x)                                      # 对象的size 是相同的，只是值和类型发生了变化

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.2322, -2.4226, -0.7515],
        [-0.3794, -0.3359,  0.3067],
        [ 0.0671, -0.5058,  0.1463],
        [ 1.6475, -0.5630, -0.1529],
        [ 0.2895,  0.4603, -1.1208]])


获取 size

***使用size方法与Numpy的shape属性返回的相同，张量也支持shape属性***


In [8]:
print(x.size())

torch.Size([5, 3])


In [10]:
x.shape

torch.Size([5, 3])

<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` 返回值是 tuple类型, 所以它支持tuple类型的所有操作.</p></div>

## 操作

**加法1**:

In [12]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.9304, -1.9350, -0.2173],
        [ 0.0465,  0.0933,  0.5559],
        [ 0.4881,  0.3155,  0.9061],
        [ 2.3044,  0.2670,  0.8461],
        [ 0.5675,  0.5983, -0.9829]])


**加法2**

In [13]:
print(torch.add(x, y))

tensor([[ 1.9304, -1.9350, -0.2173],
        [ 0.0465,  0.0933,  0.5559],
        [ 0.4881,  0.3155,  0.9061],
        [ 2.3044,  0.2670,  0.8461],
        [ 0.5675,  0.5983, -0.9829]])


提供输出tensor作为参数



In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.9304, -1.9350, -0.2173],
        [ 0.0465,  0.0933,  0.5559],
        [ 0.4881,  0.3155,  0.9061],
        [ 2.3044,  0.2670,  0.8461],
        [ 0.5675,  0.5983, -0.9829]])


替换



In [17]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 3.1626, -4.3576, -0.9688],
        [-0.3329, -0.2426,  0.8626],
        [ 0.5553, -0.1903,  1.0524],
        [ 3.9519, -0.2959,  0.6932],
        [ 0.8570,  1.0586, -2.1037]])


<div class="alert alert-info"><h4>Note</h4><p>任何 以``_`` 结尾的操作都会用结果替换原变量.
    例如: ``x.copy_(y)``, ``x.t_()``, 都会改变 ``x``.</p></div>

你可以使用与NumPy索引方式相同的操作来进行对张量的操作



In [18]:
print(x[:, 1])

tensor([-2.4226, -0.3359, -0.5058, -0.5630,  0.4603])


``torch.view``: 可以改变张量的维度和大小

***torch.view 与 Numpy 的 reshape 类似***



In [19]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1 从其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有只有一个元素的张量，使用``.item()``来得到Python数据类型的数值


In [20]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2230])
0.2229740172624588


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy 转换
------------

将一个Torch Tensor转换为NumPy数组是一件轻松的事，反之亦然。

Torch Tensor与NumPy数组共享底层内存地址，修改一个会导致另一个的变化。

**将一个Torch Tensor转换为 Numpy 数组**



In [21]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [22]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


观察numpy数组的值是如何改变的。



In [23]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


**NumPy Array 转化成 Torch Tensor**


使用from_numpy自动转化



In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)



所有的 Tensor 类型默认都是基于CPU， CharTensor 类型不支持到
NumPy 的转换.
CUDA 张量
------------

使用``.to`` 方法 可以将Tensor移动到任何设备中



In [20]:
# is_available 函数判断是否有cuda可以使用
# ``torch.device``将张量移动到指定的设备中
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
    x = x.to(device)                       # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改

tensor([0.7632], device='cuda:0')
tensor([0.7632], dtype=torch.float64)



Autograd: 自动求导机制
===================================

PyTorch 中所有神经网络的核心是 ``autograd`` 包。

``autograd``包为张量上的所有操作提供了自动求导。
它是一个在运行时定义的框架，这意味着反向传播是根据你的代码来确定如何运行，并且每次迭代可以是不同的。


张量（Tensor）
--------

``torch.Tensor``是这个包的核心类。如果设置
``.requires_grad`` 为 ``True``，那么将会追踪所有对于该张量的操作。 
当完成计算后通过调用 ``.backward()``，自动计算所有的梯度，
这个张量的所有梯度将会自动积累到 ``.grad`` 属性。

要阻止张量跟踪历史记录，可以调用``.detach()``方法将其与计算历史记录分离，并禁止跟踪它将来的计算记录。

为了防止跟踪历史记录（和使用内存），可以将代码块包装在``with torch.no_grad()：``中。
在评估模型时特别有用，因为模型可能具有`requires_grad = True`的可训练参数，但是我们不需要梯度计算。

在自动梯度计算中还有另外一个重要的类``Function``.

``Tensor`` 和 ``Function``互相连接并生成一个非循环图，它表示和存储了完整的计算历史。
每个张量都有一个``.grad_fn``属性，这个属性引用了一个创建了``Tensor``的``Function``（除非这个张量是用户手动创建的，即，这个张量的
``grad_fn`` 是 ``None``）。

如果需要计算导数，你可以在``Tensor``上调用``.backward()``。 
如果``Tensor``是一个标量（即它包含一个元素数据）则不需要为``backward()``指定任何参数，
但是如果它有更多的元素，你需要指定一个``gradient`` 参数来匹配张量的形状。


In [25]:
import torch

创建一个张量并设置 requires_grad=True 用来追踪他的计算历史

In [47]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


对张量进行操作:

In [48]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


结果``y``已经被计算出来了，所以，``grad_fn``已经被自动生成了。

In [49]:
print(y.grad_fn)

对`y`进行一个操作

In [50]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


``.requires_grad_( ... )`` 可以改变现有张量的 ``requires_grad``属性。如果没有指定的话，默认输入的flag是 ``False``。

In [51]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


梯度
---------
**反向传播**
因为 ``out``是一个纯量（scalar），``out.backward()`` 等于``out.backward(torch.tensor(1))``。

In [52]:
out.backward()

print gradients $d(out)/dx$

In [53]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


得到矩阵 ``4.5``.调用 ``out``
*Tensor* “$o$”.

得到 $o = \frac{1}{4}\sum_i z_i$,
$z_i = 3(x_i+2)^2$ and $z_i\bigr\rvert_{x_i=1} = 27$.

因此,
$\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)$, hence
$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$.

可以使用 autograd 做更多的操作

In [77]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:  # norm 默认求2范数
    y = y * 2

print(y)

tensor([ -126.6246, -1004.7013,   153.1774], grad_fn=<MulBackward0>)


范数：

$$\|x\|_{p}=\left(\left|x_{1}\right|^{p}+\left|x_{2}\right|^{p}+\cdots+\left|x_{n}\right|^{p}\right)^{\frac{1}{p}}$$

In [78]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


如果``.requires_grad=True``但是你又不希望进行autograd的计算，
那么可以将变量包裹在 ``with torch.no_grad()``中:

In [74]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
